trigger:
  - master # <--- Changed from main to master

variables:
  - group: prod-secrets

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      docker-compose up -d --build
    env:
      MONGO_URI: $(MONGO_URI)
    displayName: "Deploy Services from Master"

  - script: |
      sleep 15
      curl -f http://localhost:3001/health || (docker-compose logs api && exit 1)
    displayName: "Verify Deployment"
