trigger:
  - master

pool:
  name: "Default" # Replace 'Default' with the name of your private Agent Pool if different

variables:
  dockerRegistryServiceConnection: "acr-conn"
  kubernetesServiceConnection: "aks-conn"
  acrHost: "threetierregistry.azurecr.io"
  tag: "$(Build.BuildId)"

stages:
  - stage: CI_CD
    jobs:
      - job: Build_And_Deploy
        steps:
          - script: |
              echo "Running Unit Tests..."
              # Add your test commands here
            displayName: "Step 1: Unit Test"

          - task: Docker@2
            displayName: "Step 2: Build and Push"
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: "threetier-app"
              command: "buildAndPush"
              tags: |
                $(tag)

          - script: |
              # Using Docker to run Trivy on your local machine
              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
              aquasec/trivy image $(acrHost)/threetier-app:$(tag)
            displayName: "Step 3: Security Scan"

          - task: KubernetesManifest@1
            displayName: "Step 4: Deploy to AKS"
            inputs:
              action: "deploy"
              connectionType: "kubernetesServiceConnection"
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: "default"
              manifests: |
                $(System.DefaultWorkingDirectory)/k8s-spec.yaml
              containers: |
                $(acrHost)/threetier-app:$(tag)
