version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI # <--- This "grabs" the secret from the Azure Agent
    networks:
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      # Since we are using a URI with credentials,
      # the DB must be initialized with the SAME credentials.
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb_data:
