version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    environment:
      # Azure Variable theke Pura Connection String-ti nibe
      - MONGO_URI=${MONGO_URI}
    networks:
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      # DB initialize korar jonno username o password
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb_data:
